# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61cdac2663683b3cd6805fdb4ee24668df097b6aea3d0df8c56e29e63ff87ae12e5c818eb00723c85bffe032d827c3b83359563df281d7fc8692e7da042b0c4e

test:
  secret_key_base: 75ab244db5c4c756a6b917d3f5078b112f01de9f8273d7a08cb235556617901f8e563f46fa4d2f0712abe70b8c922f7b988a3fa36c6fc125bee6c1b26b8ce012

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
